    steps:
    - uses: actions/checkout@v3
    - name: Scan container image with Tenable Cloud Security
      uses: ermetic/actions/container-image/scan@v1
      with:
        api-token: ${{ secrets.TENABLE_API_TOKEN }}
        api-url: https://sg.app.ermetic.com
        name: ubuntu-latest
